### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by pexcn** [Matrixx-Devices/android_kernel_xiaomi_pipa#1]
Hi, I am try to build kernel for pipa, using the aosp defconfig, but compile failed... Can you help me?
compile error log: https://github.com/pexcn/android-kernel-builder/actions/runs/14335030067/job/40179770660
here my build script: https://github.com/pexcn/android-kernel-builder/blob/master/build.sh
```
../kernel/sched/fair.c:248:40: error: too many arguments to function call, expected single argument 'cpu', have 2 arguments
  248 |         return -arch_scale_cpu_capacity(NULL, cpu);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~       ^~~
../include/linux/arch_topology.h:21:15: note: 'topology_get_cpu_scale' declared here
   21 | unsigned long topology_get_cpu_scale(int cpu)
      |               ^                      ~~~~~~~
1 error generated.
make[3]: *** [../scripts/Makefile.build:328: kernel/sched/fair.o] Error 1
make[2]: *** [../scripts/Makefile.build:632: kernel/sched] Error 2
make[1]: *** [/__w/android-kernel-builder/android-kernel-builder/build/kernel/Makefile:1249: kernel] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by CuriousNom** [comment]
As u can see, am working on repo currently for next release. it not buildable currently, try after few hours

**Comment by pexcn** [comment]
Yeah, I noticed that the current version seems to have been fixed? https://github.com/Matrixx-Devices/android_kernel_xiaomi_pipa/commit/a615805d59268028cfb690dd66662f93624a6f35

Now I am [tring to build](https://github.com/pexcn/android-kernel-builder/actions/runs/14356579082/job/40247317499)...

**Comment by CuriousNom** [comment]
Nope its not fixed yet, will take time, but will fix by today, if u still wanna build right now, dont build with latest changes, do this - git reset --hard d23d9d631187e303c2f4f8a1a71457a476007f14 , then build

**Comment by pexcn** [comment]
Thank you, I testing it now :)
